import { Inter } from 'next/font/google'
import "./globals.css"
import Link from "next/link"
//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
      <body>
      <div className = "navbar">
          
          <Link href = "/"> 홈 </Link>
          <Link href = "/list"> 목록 </Link>
          <Link href = "/write">글쓰기</Link>
         
        </div>
      
      <div className = "navbara">
      <Link href = "/" className = "logo">Appleforum</Link>
     
      </div>
        
        {children}</body>
    </html>
  )
}
